### ISSUE TITLE
Prepare Moderately compatibility

### ISSUE THREAD

**Issue by Ozzymud** [aRandomKiwi/RimSaves#5]
Just linking here to an issue from the Prepare Moderately repository...

**Description:** 

[RimSaves](https://steamcommunity.com/sharedfiles/filedetails/?id=1713367505) changes vanilla save menus, causing the [Prepare Moderately](https://steamcommunity.com/sharedfiles/filedetails/?id=2057362949) filter save menu to not display properly.

**Their Possible solution:**
Create a patch that uses RimSaves save menus when RimSaves is loaded.

**Isuue over there:** 

https://github.com/Lakuna/RimWorld-Prepare-Moderately/issues/29

**Comment by aRandomKiwi** [comment]
Thanks for the report, fixed with the latest update 67b779ce2dac1712c907ef8db3427f9391b3701d on 1.4 branch.

**Comment by Ozzymud** [comment]
OH! Just wanted to say here as I am not allowed to comment on the steam workshop (GOG owner)... Thanks for this mod! It's awesome! What game has an in-game save/load feature without F5/F9 quicksaves anyways :P Hoping vanilla eventually puts this mod out of business :P
